name: Feature Request
description: Suggest an idea for this project
title: 'Feature Request: '
labels: [enhancement]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a feature request. Please make sure you provide enough information so that we can understand your suggestion and take appropriate action.

  - type: input
    attributes:
      label: Title of the Feature Request
      placeholder: e.g. "Add dark mode option"

  - type: textarea
    attributes:
      label: Description
      placeholder: A detailed description of the feature you would like to see added to the project.
